name: Build Linux 6.1
on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install docker
        run: |
          sudo apt update -y -qqq
          sudo apt autoremove --purge needrestart;
          sudo apt install -y -qqq bash wget ca-certificates curl git
          sudo ln -svf bash /bin/sh
          sudo bash docker/.pre
          sudo bash docker/install_docker.sh

      - name: Build kernel 6.1 el8
        run: |
          echo
          sudo df -h
          echo
          sudo lsblk
          echo
          sudo docker info
          echo
          sudo bash linux-6.1/run-build-el8.sh
          echo
          sudo df -h
          echo
          sudo systemctl stop docker.socket docker.service containerd.service
          sudo rm -fr /var/lib/docker/*

      - name: Upload kernel 6.1 el8
        run: |
          _repo="$(echo ${{ github.repository }} | awk -F '/' '{print $2}')"
          _kernel_ver="$(sudo ls -1 /home/.tmp.kernel/_output/kernel/assets/kernel-* | sed -e 's|.*kernel-||g' -e 's|-repo.*||g' | tail -n1)"
          sudo ls -1 /home/.tmp.kernel/_output/kernel/assets/kernel-* | sudo xargs --no-run-if-empty -I '{}' sudo bash .upload_gh -f '{}' -u "${{ github.repository_owner }}" -r "${_repo}" -t "v${_kernel_ver}" -k "${{ secrets.GITHUB_TOKEN }}"
          sudo ls -1 /home/.tmp.kernel/_output/kernel/kernel-*-repos/packages/* | sudo xargs --no-run-if-empty -I '{}' sudo bash .upload_gh -f '{}' -u "${{ github.repository_owner }}" -r "${_repo}" -t "v${_kernel_ver}" -k "${{ secrets.GITHUB_TOKEN }}"

