name: Build Linux 6.1
on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install docker
        run: |
          sudo apt update -y -qqq
          sudo apt autoremove --purge -y dotnet-apphost-pack-6.0 || true 
          sudo apt autoremove --purge -y dotnet-apphost-pack-7.0 || true 
          sudo apt autoremove --purge -y dotnet-host || true 
          sudo apt autoremove --purge -y dotnet-hostfxr-6.0 || true 
          sudo apt autoremove --purge -y dotnet-hostfxr-7.0 || true 
          sudo apt autoremove --purge -y dotnet-runtime-6.0 || true 
          sudo apt autoremove --purge -y dotnet-runtime-7.0 || true 
          sudo apt autoremove --purge -y dotnet-runtime-deps-6.0 || true 
          sudo apt autoremove --purge -y dotnet-runtime-deps-7.0 || true 
          sudo apt autoremove --purge -y dotnet-sdk-6.0 || true 
          sudo apt autoremove --purge -y dotnet-sdk-7.0 || true 
          sudo apt autoremove --purge -y dotnet-targeting-pack-6.0 || true 
          sudo apt autoremove --purge -y dotnet-targeting-pack-7.0 || true 
          sudo apt autoremove --purge -y google-chrome-stable || true 
          sudo apt autoremove --purge -y google-cloud-sdk || true 
          sudo apt autoremove --purge -y libmono-microsoft-build4.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-build-engine4.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-build-framework4.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-build-tasks-v4.0-4.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-build-utilities-v4.0-4.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-csharp4.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-visualc10.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-web-infrastructure1.0-cil || true 
          sudo apt autoremove --purge -y libmono-sqlite4.0-cil || true 
          sudo apt autoremove --purge -y libmono-system-json-microsoft4.0-cil || true 
          sudo apt autoremove --purge -y libmspack0 || true 
          sudo apt autoremove --purge -y libpq5 || true 
          sudo apt autoremove --purge -y libpq-dev || true 
          sudo apt autoremove --purge -y libsybdb5 || true 
          sudo apt autoremove --purge -y libz3-4 || true 
          sudo apt autoremove --purge -y libz3-dev || true 
          sudo apt autoremove --purge -y microsoft-edge-stable || true 
          sudo apt autoremove --purge -y mono-roslyn || true 
          sudo apt autoremove --purge -y msodbcsql17 || true 
          sudo apt autoremove --purge -y mssql-tools || true 
          sudo apt autoremove --purge -y mysql-client || true 
          sudo apt autoremove --purge -y mysql-client-8.0 || true 
          sudo apt autoremove --purge -y mysql-client-core-8.0 || true 
          sudo apt autoremove --purge -y mysql-common || true 
          sudo apt autoremove --purge -y mysql-server || true 
          sudo apt autoremove --purge -y mysql-server-8.0 || true 
          sudo apt autoremove --purge -y mysql-server-core-8.0 || true 
          sudo apt autoremove --purge -y nginx || true 
          sudo apt autoremove --purge -y nginx-common || true 
          sudo apt autoremove --purge -y packages-microsoft-prod || true 
          sudo apt autoremove --purge -y php8.1-mysql || true 
          sudo apt autoremove --purge -y php8.1-pgsql || true 
          sudo apt autoremove --purge -y php8.1-sqlite3 || true 
          sudo apt autoremove --purge -y postgresql-14 || true 
          sudo apt autoremove --purge -y postgresql-client-14 || true 
          sudo apt autoremove --purge -y postgresql-client-common || true 
          sudo apt autoremove --purge -y postgresql-common || true 
          sudo apt autoremove --purge -y powermgmt-base || true 
          sudo apt autoremove --purge -y powershell || true 
          sudo apt autoremove --purge -y python3-configobj || true 
          sudo apt autoremove --purge -y shim-signed || true 
          sudo apt autoremove --purge -y firefox || true 
          sudo /bin/rm -fr /usr/share/sbt
          sudo /bin/rm -fr /usr/share/gradle*
          sudo /bin/rm -fr /usr/share/miniconda*
          sudo /bin/rm -fr /usr/share/az_*
          sudo /bin/rm -fr /usr/share/swift*
          sudo /bin/rm -fr /usr/share/dotnet*
          sudo /bin/rm -fr /usr/lib/snapd
          sudo /bin/rm -fr /usr/lib/firefox
          sudo /bin/rm -fr /usr/lib/llvm*
          sudo /bin/rm -fr /usr/lib/mono
          sudo /bin/rm -fr /usr/lib/jvm
          sudo /bin/rm -fr /usr/lib/google-cloud-sdk*
          sudo /bin/rm -fr /opt/containerd
          sudo /bin/rm -fr /opt/mssql-tools
          sudo /bin/rm -fr /opt/google
          sudo /bin/rm -fr /opt/pipx
          sudo /bin/rm -fr /opt/az
          sudo /bin/rm -fr /opt/microsoft
          sudo /bin/rm -fr /usr/local/sqlpackage
          sudo /bin/rm -fr /usr/local/n
          sudo /bin/rm -fr /usr/local/aws*
          sudo /bin/rm -fr /usr/local/julia*
          sudo /bin/rm -fr /usr/local/share
          sudo /bin/rm -fr /usr/local/.ghcup
          sudo /bin/rm -fr /opt/hostedtoolcache
          sudo apt install -y -qqq bash wget ca-certificates curl git
          sudo ln -svf bash /bin/sh
          sudo bash docker/.pre
          sudo bash docker/install_docker.sh

      - name: Build kernel 6.1 el8
        run: |
          echo
          sudo df -h
          echo
          sudo lsblk
          echo
          sudo docker info
          echo
          sudo bash linux-6.1/run-build-el8.sh
          echo
          sudo df -h
          echo
          sudo systemctl stop docker.socket docker.service containerd.service
          sudo rm -fr /var/lib/docker/*
      - name: Upload kernel 6.1 el8
        run: |
          _repo="$(echo ${{ github.repository }} | awk -F '/' '{print $2}')"
          _kernel_ver="$(sudo ls -1 /home/.tmp.kernel/_output/kernel/assets/kernel-* | sed -e 's|.*kernel-||g' -e 's|-repo.*||g' | tail -n1)"
          sudo ls -1 /home/.tmp.kernel/_output/kernel/assets/kernel-* | sudo xargs --no-run-if-empty -I '{}' sudo bash .upload_gh -f '{}' -u "${{ github.repository_owner }}" -r "${_repo}" -t "v${_kernel_ver}" -k "${{ secrets.GITHUB_TOKEN }}"
          sudo ls -1 /home/.tmp.kernel/_output/kernel/kernel-*-repos/packages/* | sudo xargs --no-run-if-empty -I '{}' sudo bash .upload_gh -f '{}' -u "${{ github.repository_owner }}" -r "${_repo}" -t "v${_kernel_ver}" -k "${{ secrets.GITHUB_TOKEN }}"

